
language: python
#addons:
#  apt:
#    packages:
#    - python3-dev
#    - libgnutls28-dev
python:
  - "3.7"
before_install:
  - sudo apt-get update -q
  - sudo apt-get -y install python3-dev 
  - sudo apt-get -y install libgnutls28-dev
    
# command to run tests
install: pip install -r requirements.txt
script: pytest ./Tests/test_onreceive.py
# runs all but needs connection to cameras
#script: pytest
